branches:
  only:
  - master
language: node_js
node_js:
- '15.3'

sudo:
  required

cache:
  npm: true

before-script:
- npm add grunt
- npm add grunt-cli
- npm add typescript
- npm add grunt-ts
- npm install

script:
- grunt --gruntfile Gruntfile.cjs l4w-build-pipeline

after_success:
- bash post_build.sh

env:
  global:
  - secure: U6TOPyH+FlIFJmfii3w1u9yva9piqMW22Qmw8CBrGeyX8WHpj/VEn8RQBmu0GRPj2O6aBXNkSbNIeD27DTqFbHUMjPxbJW+aJNxrChH7TKnOrrZuafNGVWAFM2QOrrqwY/wfGhLm7W5j13r8zOeqiT0dMUvqA9recsov0uzxdg4im602GRR4Di8OWHRPRlRBqnL71iGlWq3DvGdQq9wkYrFePW16uKb1B9zYlTjwHjjMp2lUAxFECh9lmxbiqsRAom3AWVTxjZnk1kqHEsVCHCT5Ye1T1jB2oucHgtPcLXzSnBiFRyGLCbX90Dxp3yXOgwptNPpeR0sjsvyi5aqcKyX+N5gHMaQnJKploMMaHHMR5q9Ji531kd3qNwNwjzg/SlxFeljiMPEIMoEniZHnb3j9geiqmMVd174VeRT8qTHvhbv0PokPY6yVlPjkTNbM4sx251Dr+58bR/MNVDtwtgSII4smuWlc7WexM3ZY/vsVmtAGYGSUaRd9be49eATGWkgW0AemRo+lQwWgoKtvwzWlQaDuIaD1AqPMqhZ3ITkNJvajGN1/qipfipMfptJF1rC2QG3ZKmvyPfiQChdnLYlvMR1qA3Pf18rhdWcsoxZvnedaGwjyDGvv4QWLYGRQfunn3PQjfFAumUEDPK+lVad1LHWLceAE2/5KdGBA8vk=

notifications:
  email: false
